// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7_24QY2oBx-XXarylXLjfg-L6mNxNymw',
    appId: '1:628993855406:web:5b3b963d9b63e77c31023f',
    messagingSenderId: '628993855406',
    projectId: 'appforzadb',
    authDomain: 'appforzadb.firebaseapp.com',
    storageBucket: 'appforzadb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgonPTNgg59kFwUiPgUZSbMPcrdP-slD0',
    appId: '1:628993855406:android:0fdcdaef2dc530f831023f',
    messagingSenderId: '628993855406',
    projectId: 'appforzadb',
    storageBucket: 'appforzadb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWXY4RTGQ8FAwSV_J3QDb4utGfSeBuHqA',
    appId: '1:628993855406:ios:69fac50234b9539f31023f',
    messagingSenderId: '628993855406',
    projectId: 'appforzadb',
    storageBucket: 'appforzadb.appspot.com',
    iosClientId: '628993855406-60fo9kn10qt8gulc833nc1h819esh49p.apps.googleusercontent.com',
    iosBundleId: 'com.example.forza',
  );
}
